/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bmxiukljsaszintthiqo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJteGl1a2xqc2FzemludHRoaXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY2MDE4NTQsImV4cCI6MjA5MjE3Nzg1NH0.PzSIZJvp97-cS1547-aBXSawCNKjfe20d82CxhSIp0g"